#### Note - Please change the hardcoded location before running the program

# Importing required libaries

In [56]:
import pandas as pd
import numpy as np
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import LinearSVC

# Displaying dimensions and basic statistics of train and test data

In [57]:
# loading given train and test dataset
train_df = pd.read_csv(r'C:\AI\case_study\multiclass_classification\train.csv')
test_df = pd.read_csv(r'C:\AI\case_study\multiclass_classification\test.csv')

In [58]:
# displaying shape/dimension of train and test data
print(train_df.shape, test_df.shape)
train_df.head()

((7200, 252), (4800, 251))

,id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature241,feature242,feature243,feature244,feature245,feature246,feature247,feature248,feature249,label
0,0,25.208249,-16.745748,50.869944,5.593472,1.188263,-6.014167,15.922007,-42.026918,-0.064017,...,6.731995,4.805149,-9.682240,-8.771275,159.124491,3.682115,-4.938090,130.068955,-8.231081,1
1,1,-86.931450,0.428227,2.874836,-8.064850,6.056867,6.124567,2.527879,-9.277728,-7.586313,...,-6.274857,-9.967576,-70.256324,-5.278519,-53.004625,6.484784,-6.389429,-26.164277,-4.909740,2
2,2,42.160934,7.857013,151.612757,9.639676,5.570139,-3.261364,10.814200,-37.394430,-5.791044,...,9.362207,18.524639,39.445002,-1.980687,-7.543595,-1.971843,8.034066,120.510705,7.754377,0
3,3,20.666944,8.680642,-56.449179,-9.814780,-2.382979,-14.596355,-3.621941,49.598995,11.138753,...,0.035327,11.019507,-2.254336,2.216576,65.238695,7.029985,8.940062,-40.426248,5.557971,1
4,4,35.946679,4.573736,-28.160212,-6.912971,4.879375,-0.131064,-2.509488,10.334908,-1.738533,...,-14.119385,-12.166055,50.745103,-2.205711,69.052119,-6.407847,3.399937,-23.468499,-11.269110,0

In [59]:
# displaying basic statistics of train data
train_df.describe()

,id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature241,feature242,feature243,feature244,feature245,feature246,feature247,feature248,feature249,label
count,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,...,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000,7200.000000
mean,3599.500000,2.504684,0.615413,3.016680,0.243273,-0.158600,0.506224,-0.276842,0.540687,0.608447,...,0.605181,-0.020437,-0.958585,-0.260203,-4.950015,-0.159411,0.672097,3.745077,0.273164,2.009167
std,2078.605302,67.755261,8.231712,65.188459,8.518782,8.190667,8.356110,8.365744,67.375739,8.133119,...,8.200987,8.390035,64.426649,8.162079,65.950715,8.218073,8.067559,69.372084,8.282975,1.411923
min,0.000000,-236.552276,-28.061843,-226.049557,-28.452153,-33.186906,-27.092009,-31.324360,-244.329485,-27.871326,...,-30.405404,-31.543493,-258.567376,-30.154402,-248.161392,-33.408119,-31.436556,-295.175132,-29.377652,0.000000
25%,1799.750000,-42.590075,-5.004813,-39.828719,-5.587758,-5.582504,-5.227875,-5.904324,-45.382821,-4.945470,...,-5.005272,-5.718761,-44.261020,-5.763305,-49.965317,-5.703261,-4.710237,-43.293031,-5.408092,1.000000
50%,3599.500000,2.920268,0.562655,2.704124,0.292459,-0.117978,0.566189,-0.201625,0.954221,0.567095,...,0.498952,0.011173,-0.394964,-0.401264,-5.736435,-0.094127,0.574117,5.055538,0.182123,2.000000
75%,5399.250000,48.558923,5.964513,46.821744,5.858455,5.371252,6.195204,5.357205,46.362046,6.066210,...,6.002283,5.655573,42.170790,5.331488,39.989426,5.384608,6.003897,49.078444,5.772318,3.000000
max,7199.000000,261.350410,32.566261,249.443153,29.926784,37.680869,28.115217,34.307626,269.012188,32.139129,...,36.079314,32.325529,243.347500,33.403021,223.734432,29.623627,30.877309,244.195967,28.088101,4.000000

In [60]:
# displaying basic statistics of test data
test_df.describe()

,id,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,...,feature240,feature241,feature242,feature243,feature244,feature245,feature246,feature247,feature248,feature249
count,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,...,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000
mean,9599.500000,3.542617,0.546814,4.282615,0.084436,-0.154362,0.687599,-0.292732,2.816511,0.607590,...,-0.378327,0.555431,-0.088492,-1.685285,-0.282409,-4.665585,-0.334963,0.710662,1.559336,0.065233
std,1385.784976,67.806072,8.301816,66.000187,8.326892,8.267483,8.375432,8.250653,67.744648,7.985628,...,8.234161,8.177108,8.435206,63.417726,8.219512,65.331821,8.115676,8.028090,67.973338,8.368147
min,7200.000000,-240.652973,-30.811456,-209.826401,-28.954392,-33.351535,-28.020731,-30.566554,-219.371051,-26.465960,...,-28.563462,-28.159985,-26.335970,-250.289664,-29.122300,-252.498365,-29.200745,-27.029203,-255.408965,-33.438004
25%,8399.750000,-41.549446,-4.824596,-40.260351,-5.363470,-5.746345,-4.931357,-5.724133,-43.389461,-4.672855,...,-6.001584,-4.912250,-5.745404,-44.488764,-5.595674,-49.803184,-5.807474,-4.778246,-44.003087,-5.281672
50%,9599.500000,3.385332,0.521586,4.433871,0.066457,-0.187414,0.725743,-0.127263,2.179941,0.778574,...,-0.355036,0.572281,-0.232225,-2.135615,-0.287745,-5.543748,-0.438899,0.813090,0.884138,-0.091334
75%,10799.250000,49.113276,6.036709,48.177122,5.581335,5.527515,6.325243,5.211910,48.900874,5.889594,...,5.226240,6.079080,5.471616,40.839269,5.076436,39.171215,5.037820,6.154775,47.193176,5.584674
max,11999.000000,308.112386,30.792156,223.295745,33.451326,27.779232,30.464026,36.316996,277.496622,28.997294,...,29.248194,31.841251,28.894166,217.148909,30.781810,234.375266,30.064176,28.337236,250.174044,29.463977

In [61]:
train_df.drop(train_df.columns[0], axis = 1, inplace = True) # dropping id column since we only need features of dataset

In [62]:
features = [f for f in list(train_df) if "feature" in f] # storing all the features in features variable using list comprehensions
X = train_df[features] # passing features of traindata and storing in X variable
y = train_df["label"] # storing label columns in y variable
train_df.head() # displaying train dataframe

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature241,feature242,feature243,feature244,feature245,feature246,feature247,feature248,feature249,label
0,25.208249,-16.745748,50.869944,5.593472,1.188263,-6.014167,15.922007,-42.026918,-0.064017,-6.492815,...,6.731995,4.805149,-9.682240,-8.771275,159.124491,3.682115,-4.938090,130.068955,-8.231081,1
1,-86.931450,0.428227,2.874836,-8.064850,6.056867,6.124567,2.527879,-9.277728,-7.586313,-1.802893,...,-6.274857,-9.967576,-70.256324,-5.278519,-53.004625,6.484784,-6.389429,-26.164277,-4.909740,2
2,42.160934,7.857013,151.612757,9.639676,5.570139,-3.261364,10.814200,-37.394430,-5.791044,0.073638,...,9.362207,18.524639,39.445002,-1.980687,-7.543595,-1.971843,8.034066,120.510705,7.754377,0
3,20.666944,8.680642,-56.449179,-9.814780,-2.382979,-14.596355,-3.621941,49.598995,11.138753,-7.247519,...,0.035327,11.019507,-2.254336,2.216576,65.238695,7.029985,8.940062,-40.426248,5.557971,1
4,35.946679,4.573736,-28.160212,-6.912971,4.879375,-0.131064,-2.509488,10.334908,-1.738533,-3.376448,...,-14.119385,-12.166055,50.745103,-2.205711,69.052119,-6.407847,3.399937,-23.468499,-11.269110,0

In [63]:
test_df.drop(test_df.columns[0], axis = 1, inplace = True) # dropping id column since we only need features of dataset

In [64]:
features = [f for f in list(test_df) if "feature" in f] # storing all the features in features variable using list comprehensions
X_test = test_df[features] # passing features of testdata and storing in X_test variable
X_test.head() # displaying test dataframe

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature240,feature241,feature242,feature243,feature244,feature245,feature246,feature247,feature248,feature249
0,-76.795547,-12.319618,-109.961631,-11.006934,-8.770868,-1.246577,3.875265,33.877412,7.757658,-4.003451,...,5.515601,10.530372,6.887168,-76.231907,3.374217,-128.668656,6.001156,2.619267,-14.869630,-4.718944
1,15.860563,-5.344301,74.481876,1.267520,7.044210,6.391507,-7.713534,-1.336639,1.197008,1.246036,...,-4.515135,4.041697,-9.170853,-38.501120,0.036281,22.997648,-4.050474,-16.322332,-54.813692,14.470087
2,21.243900,-7.539082,-13.128054,-7.283449,1.430600,8.113846,-7.219935,-83.107625,-7.449005,-4.787342,...,-1.748731,-2.171528,16.292004,30.960787,0.380944,-86.906365,14.387590,-3.615364,160.603909,-11.330304
3,8.999656,-0.397410,-31.769650,3.873494,0.255903,-5.713813,2.786370,28.037992,3.583793,-1.226325,...,19.629190,-0.578924,8.683254,1.959471,2.281506,-79.247118,-2.850041,-10.813797,-69.974758,-1.369170
4,34.330833,-4.469938,-9.004407,-10.726552,-0.845002,0.722776,-1.836055,19.510244,2.785751,-2.895020,...,-5.110906,-2.840026,-7.043582,-28.169285,0.745229,70.852868,-5.185859,2.662763,-20.369640,7.001808

# fitting the model and validating score (spotchecking)

Random Forest Classifier

In [65]:
rand_clf = RandomForestClassifier(n_jobs = 10) # creating random forest with 10 decision tree
rand_clf.fit(X,y) # fitting the random forest on train data
print "Random forest accuracy_score:", rand_clf.score(X, y) # printing the score of RandomForestClassifier

Random forest accuracy_score: 0.993888888889

Gradient Boosting Classifier

In [66]:
gb_clf= GradientBoostingClassifier(random_state=0).fit(X, y)  # fitting the GradientBoosting on train data
print "GradientBoostingClassifier accuracy_score:", gb_clf.score(X, y) # printing the score of GradientBoosting Classifier

GradientBoostingClassifier accuracy_score: 0.959027777778

Linear SVC(OneVsOneClassifier)

In [67]:
one_vs_one_svc = OneVsOneClassifier(LinearSVC()) # passing LinearSVC to OneVsOneClassifier as an input
one_vs_one_svc.fit(X, y) # fitting the  OneVsOneClassifier on train data
print "LinearSVC(OneVsOne) accuracy_score:", one_vs_one_svc.score(X, y) # printing the score of GradientBoosting Classifier

LinearSVC(OneVsOne) accuracy_score: 0.832916666667

# saving and loading the model

In [68]:
# save the random_forest_model to disk
filename = r'C:\AI\case_study\multiclass_classification\random_forest_classifier.sav'
pickle.dump(rand_clf, open(filename, 'wb'))

# load the random_forest_model from disk
loaded_model = pickle.load(open(filename, 'rb'))
rand_score = loaded_model.score(X, y)
print(rand_score)

0.993888888889

In [69]:
# save the gb_model to disk
filename = r'C:\AI\case_study\multiclass_classification\gb_classifier.sav'
pickle.dump(gb_clf, open(filename, 'wb'))

# load the gb_model from disk
loaded_model = pickle.load(open(filename, 'rb'))
gb_score = loaded_model.score(X, y)
print(gb_score)

0.959027777778

In [70]:
# save the svc_model to disk
filename = r'C:\AI\case_study\multiclass_classification\one_vs_one_classifier.sav'
pickle.dump(one_vs_one_svc, open(filename, 'wb'))

# load the svc_model from disk
loaded_model = pickle.load(open(filename, 'rb'))
svc_score = loaded_model.score(X, y)
print(svc_score)

0.832916666667

# Accuracy Report

In [71]:
accuracy_report = {'Model': ['Random Forest', 'GradientBoosting', 'OneVsOneClassifier(SVC)'],
         'model_accuracy': [rand_score, gb_score, svc_score]}
df = pd.DataFrame.from_dict(accuracy_report)
df

                     Model  model_accuracy
0            Random Forest        0.993889
1         GradientBoosting        0.959028
2  OneVsOneClassifier(SVC)        0.832917

# Testing all the models on the given test data

In [72]:
result_df = test_df.copy(deep=True)

In [73]:
rand_label = rand_clf.predict(test_df)
gb_label = gb_clf.predict(test_df)
svc_label = one_vs_one_svc.predict(test_df)
result_df['rand_forest'] = rand_label
result_df['GB_label'] = gb_label
result_df['svc_label'] = svc_label
result_df.to_csv(r'C:\AI\case_study\multiclass_classification\result_all_model.csv')

# Final Model selected (Random Forest)

### Please load saved model given by me to see random_forest_result.csv file

In [74]:
filename = r'C:\AI\case_study\multiclass_classification\random_forest_classifier.sav' # pass saved model location to filename variable
pickle.dump(rand_clf, open(filename, 'wb')) #dump the saved model using pickle

# load the random_forest_model from disk
rand_model = pickle.load(open(filename, 'rb'))
rand_label = rand_model.predict(test_df) # saving predict result of test_df to rand_label variable
randresult_df = test_df.copy(deep=True)
rand_result_df['rand_forest'] = rand_label #passing the result to newly created colummn rand_forest
print ("starting......")
rand_result_df.to_csv(r'C:\AI\case_study\multiclass_classification\random_forest_result.csv') # saving the test result
print ("testing on entire dataset is completed... please goto saved location to see result")
rand_score = rand_model.score(X, y) #printing score
print "Random forest accuracy_score:", rand_score

starting......
testing on entire dataset is completed... please goto saved location to see result
Random forest accuracy_score: 0.993888888889